### PR TITLE
use computed-types instead of funval

### PR DESCRIPTION
**Pull request by moshest**

### CODE REVIEW

**Comment by moltar** [comment]
@moshest do you mind resolving the merge conflicts?

Sorry, I think @dependabot had created a lot of PRs that cannot be merged now.

**Comment by moshest** [comment]
There are no conflicts now..

**Comment by moltar** [comment]
I get:

> This branch cannot be rebased due to conflicts

image

**Comment by moshest** [comment]
image

this is the last commit:
https://github.com/moltar/typescript-runtime-type-benchmarks/pull/276/commits/51e2af7abdb87f01dde046895e1aec56d5013601

**Comment by moltar** [comment]
Hm ... strange. Maybe it's a GH caching issue?

**Comment by moltar** [comment]
Ok, I had it set to rebase, which is what I normally do. But a merge does work.

**Pull request merged**
