### PR TITLE
feat: adds rulr

### PR DESCRIPTION
**Pull request by ryansmith94**
Hey Roman. I've fixed Rulr for TS v4, thanks for reporting the issue in ryansmith94/rulr#251. I've tried to keep this close to #339 to revert the change in edc5b5b160cdc0fa7988ed78dae44cd3cdd96e23. Let me know if it needs anything else, I need to try to remember how to generate the results locally.

Edit: I think I'm struggling to generate the results locally after that last Renovate update.

### CODE REVIEW

**Comment by moltar** [comment]
Awesome! Thanks @ryansmith94!

**Comment by ryansmith94** [comment]
No worries 👍 let me know if I can do anything to help fix the builds on master.

**Comment by moltar** [comment]
> No worries 👍 let me know if I can do anything to help fix the builds on master.

Hm, I didn't even realize master was broken. Oops.

When I run build and tests locally - everything is fine.

But on GH it fails.

If you could help figuring out why, that would be extremely helpful.

I am a new father, so time is extremely limited now :(

**Comment by ryansmith94** [comment]
Hey @moltar. No worries, congratulations!

I've had a look at the issue and it seems to be caused by the breaking changes in [svgo v2](https://github.com/svg/svgo/releases/tag/v2.0.0). Two options to resolve this.

1. Change the code using svgo.
2. Downgrade svgo.

Option 1 has issues because [@types/svgo](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/svgo) has not been updated yet for svgo v2. The quick fix is to just ignore the TSC warnings on that one import for now. The long fix is to implement the typings temporarily in this repo. I've got with the option 1 and the quick fix for now, just making a PR for you.

**Comment by moltar** [comment]
Hey @ryansmith94, thanks for looking into this. Much appreciated 🙌🏼

**Pull request merged**
