### PR TITLE
feat: add typia

### PR DESCRIPTION
**Pull request by samchon**
Related issues:

  - https://github.com/moltar/typescript-runtime-type-benchmarks/issues/898
  - https://github.com/moltar/typescript-runtime-type-benchmarks/issues/1019
  - https://github.com/samchon/typia/issues/473

I can't see benchmark result because I am using Windows PC and this repo be broken on the Windows PC.

Hope to be the fastest.

### CODE REVIEW

**Review by samchon — COMMENTED** [review]
Passed to test program in my local.

**Comment by samchon** [comment]
As other validation libraries do not allow undefined value assignment on superfluous peoperty, `typia` also blocked it by supporting extra options.

```typescript
interface Member {
    id: string;
    name: string;
    age?: number;
}

const member: Member = {
    id: "some-id",
    name: "some-name",
    age: undefined
};
// possible in typia
// not possible in other validators
// therefore, added an extra option blocking the undefined value
```

**Review by samchon — COMMENTED** [review]
As other validation libraries do not allow undefined value assignment on superfluous peoperty, `typia` also blocked it by supporting extra options.

```typescript
interface Member {
    id: string;
    name: string;
    age?: number;
}

const member: Member = {
    id: "some-id",
    name: "some-name",
    age: undefined
};
// possible in typia
// not possible in other validators
// therefore, added an extra option blocking the undefined value
```

**Comment by moltar** [comment]
@samchon The tests pass! 🎉 

But now that I understand typia more, I am a bit hesitant to merge this, as I am not 100% confident this package goes with the theme of the rest of the packages here. The theme was defining types as code, and then allowing TypeScript to infer the types. However, I do like the typia approach, and especially, because it is so much faster. I am just wondering if perhaps we need an entirely new category of validators now?

@hoeck Thoughts?

**Comment by samchon** [comment]
Well, this repository already had accepted [ts-runtime-checks](https://github.com/GoogleFeud/ts-runtime-checks) which requires `ttypescript`, too.

**Comment by hoeck** [comment]
@moltar Yeah, instead of using function composition, it directly parses interfaces at compile time, similar to the runtime type reflection that deepkit does. Using that info, it generates code similar to e.g. spectypes.

So for me, typia fits the runtype category, event though it is much more meta than more conventional (zod, valita) approaches:

:heavy_check_mark: the type is only written out once
:heavy_check_mark: a validator / casting function is provided

There are even more unconventional approaches to runtypes out there, e.g. [arktype](https://github.com/arktypeio/arktype) that mixes function composition and template literal types.

Having them all in a single basic benchmark is IMHO a really useful resource and to me would be more important than  strict inclusion criteria. It helps comparing all the different approaches, is a good showcase for the TS ecosystem and helps developers new to runtypes to maybe pick a good library that fits their use case.

> I am just wondering if perhaps we need an entirely new category of validators now?
I'd love to have a feature matrix of all benchmarked runtypes embedded in the benchmark graph, e.g. "uses runtime eval", "requires compilation step", "# of dependencies", "supports recursion" etc. to be able to better compare the different libraries and their perf / complexity trade offs.

**Comment by hoeck** [comment]
@samchon having more benchmark cases would be great but on the other hand implementing them for all libraries and presenting (weighing?) the resulting data in a useful way would be a lot of work. I'd love to do it but my time is quite limited.

**Comment by moltar** [comment]
Ok, now that I am more fresh-minded & after reading @hoeck take, I agree this fits with the theme!

> Don't you have any plan to add more test case structures like below?

There are no plans, but definitely something I'd like to see!

I think we have an issue tracking it already, and you opened it: #900

**Pull request merged**
