### PR TITLE
Minenwerfer/update aeria

### PR DESCRIPTION
**Pull request by minenwerfer**
This PR updates Aeria version.

### CODE REVIEW

**Comment by DarkGL** [comment]
Bun test is failing, you could try to update it to newest version

**Comment by minenwerfer** [comment]
> Bun test is failing, you could try to update it to newest version
> 
> Also please check `package-lock.json` conflict

Something was wrong with my esm bundling. Thanks for letting me know.
I'm fixing everything now.

**Comment by DarkGL** [comment]
I have upgraded bun version in this PR https://github.com/moltar/typescript-runtime-type-benchmarks/pull/1355

**Comment by minenwerfer** [comment]
@DarkGL bun tests are now passing. I believe the package-lock.json conflict is also fixed.

**Comment by DarkGL** [comment]
Great work :) ! I will merge it when currently running actions complete

**Comment by DarkGL** [comment]
Unfortunately bun test failed

**Comment by minenwerfer** [comment]
> Unfortunately bun test failed

After looking up I found that the `bun install` contained in the CI installs an outdated version of a dependency package. I'm sorry for the mistake, will push again soon.

**Comment by minenwerfer** [comment]
Solved the problem by removing `bun.lockb` and then running `bun install`.

**Comment by DarkGL** [comment]
Looks like there is still conflict for `bun.lockb`

**Comment by minenwerfer** [comment]
> Looks like there is still conflict for `bun.lockb`

Sorry for bothering you once again but do you have any ideas on how to solve this?
Seemed to me deleting `bun.lockb` and reinstalling was the only solution. The renovate bot fails because @aeriajs/types is still present in the package.json.

**Comment by DarkGL** [comment]
Try to merge main/master to your branch and then reinstall once more. 

Remember to sync your fork.

And no problem, I'm here to help :)

**Pull request closed without merging**
