### PR TITLE
Show ops as labels

### LINKED ISSUE #1101: Show operations/s as a number for each benchmark
The bar-graph is hard to read when comparing entries that are not near the best. It would be great to add the numbers as [labels](https://vega.github.io/vega-lite/docs/text.html#labels). If there is interest, I can raise a PR.

### PR DESCRIPTION
**Pull request by dbartholomae**
Fixes #1101

### CODE REVIEW

**Comment by moltar** [comment]
Thank you @dbartholomae 👍

I asked @hoeck for review as it's his area of expertise here 😀

**Comment by hoeck** [comment]
Wow, the labels look great :+1: - thanks for that.

But the prettier check fails so I can't merge it.

**Comment by moltar** [comment]
@dbartholomae Could you please run a quick `npm run lint:fix` on your PR and push? Thanks!

**Review by hoeck — APPROVED** [review]

**Comment by dbartholomae** [comment]
@hoeck @moltar I've pushed the fix.

**Pull request merged**
