### PR TITLE
feat: add `@mondrian-framework/model`

### PR DESCRIPTION
**Pull request by edobrb**
Add benchmarks for https://mondrianframework.com/docs/docs/foundamentals/model/definition

### CODE REVIEW

**Comment by edobrb** [comment]
Any chance that this will be merged?

**Comment by moltar** [comment]
Sorry, not sure why I missed it.

**Comment by moltar** [comment]
```
Error: node_modules/@mondrian-framework/model/build/type-system/custom/jwt.d.ts(2,26): error TS7016: Could not find a declaration file for module 'jsonwebtoken'. '/home/runner/work/typescript-runtime-type-benchmarks/typescript-runtime-type-benchmarks/node_modules/jsonwebtoken/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/jsonwebtoken` if it exists or add a new declaration (.d.ts) file containing `declare module 'jsonwebtoken';`
Error: Process completed with exit code 2.
```

**Comment by edobrb** [comment]
Should be fixed now

**Comment by moltar** [comment]
lgtm!

@hoeck ?

**Pull request merged**
