### PR TITLE
This library is about testing validation, not marshalling. So this ch…

### PR DESCRIPTION
**Pull request by marcj**
…anged the benchmark to the validation method only for Marshal.

Benchmarking in Marshal validation + marshalling next to libraries that are only benchmarked with validation is not a correct benchmark.
The new ts-json-validator is able to do both as well, but only validation is benchmarked. Thus using only the validation method in Marshal is the only way to make a fair comparison.

### CODE REVIEW

**Comment by moltar** [comment]
@marcj I have released a change that breaks this PR.

Also please remove the changes in `results/` dir. I know they were automatically generated. I now have changed the GitHub Action to only commit results if the action runs on this repo.

Sorry about that extra work. If you don't feel like doing it, please let me know and I'll just make these changes myself. Might be faster, but I also didn't want to throw away your work without your approval.

Thanks.

**Comment by marcj** [comment]
The actual change is very trivial so I'd appreciate if you could apply the same directly. We can then close this PR of course.

**Comment by moltar** [comment]
@marcj Not sure if I am doing something wrong, but this doesn't seem to be doing any type guarding at all:

```ts
  validate() { // <-- return is still "any"
    const { data } = this;

    const errors = validator(data);

    if (errors.length === 0) {
      return data; // <-- this is still of "any" type
    }

    throw new Error('Invalid');
  }
```

**Comment by marcj** [comment]
Yes, because validation and type guarding are two different topics. I've added type guards in Marshal now and create a new PR.

**Comment by moltar** [comment]
> Yes, because validation and type guarding are two different topics.

That is true. But I only care about cases where both of those are working together. 😄

**Pull request closed without merging**
