### PR TITLE
feat: adds `succulent@0.18`

### PR DESCRIPTION
**Pull request by aslilac**
Hello!

Just wanted to add another contender to the ranking :)

### CODE REVIEW

**Comment by moltar** [comment]
Hey @aslilac, thank you for your contribution! 🙌🏼 

There is a test failure:

```
● all cases must have been imported in tests

    expect(received).toBe(expected) // Object.is equality

    Expected: 38
    Received: 37

      49 |       )
      50 |     ).size
    > 51 |   ).toBe(cases.length);
         |     ^
      52 | });
      53 |
      54 | getRegisteredBenchmarks().forEach(([benchmarkId, benchmarkCases]) => {

      at Object.<anonymous> (test/benchmarks.test.ts:51:5)
```

I'm sorry we don't have great docs on the exact things that are required for the build to pass.

The easiest, for now, is to follow another successfully merged PR.

A good recent example: #1013

If you get stuck and need help, please ping back!

**Comment by aslilac** [comment]
Thanks for the reference! I almost forgot to update the README list 😆

**Comment by aslilac** [comment]
oh, safe and loose are still expected to throw?

In parseStrict.ts there's a comment saying "Like parseSafe but throw on unknown (extra) keys in objects." which I took to mean `parseSafe` shouldn't throw.

**Comment by moltar** [comment]
> supposed to prune extra keys I suppose

Yeah, that's it! Remove anything that's not part of the defined schema.

Could be a useful thing in certain scenarios. Without it can lead to some nasty injections. E.g.:

```ts
const user = {
  username: 'foo',
  is_admin: true, // ⬅️ this wasn't in the schema
}

OrmUser.save(user)

```

**Comment by moltar** [comment]
Anyhow, tests pass!! 🎉 Thank your efforts!

**Pull request merged**
