### PR TITLE
Updated Node.js versions and workflows

### PR DESCRIPTION
**Pull request by DarkGL**
- Added Node.js 21 and 22
- Updated actions in workflows

### CODE REVIEW

**Review by moltar — APPROVED** [review]

**Comment by moltar** [comment]
@hoeck Please merge if looks good

**Review by hoeck — APPROVED** [review]

**Comment by hoeck** [comment]
Thanks @DarkGL 

@moltar at some time we should also remove old Node versions. 16 and 19 are not maintained any more: https://nodejs.org/en/about/previous-releases#release-schedule

**Comment by DarkGL** [comment]
If I can add my opinion about it, I think we should leave it so people or companies who use older versions can see the benefit of upgrading, and they can show numbers which supports it.

**Comment by hoeck** [comment]
I hope that people update from unmaintained (aka insecure) to a maintained LTS version without needing any additional arguments :grin: but I get your point, kind of (have been guilty of running long outdated node versions myself).

**Pull request merged**
