### PR TITLE
feat: adds rulr

### LINKED ISSUE #337: Add rulr
https://github.com/ryansmith94/rulr

Maybe @ryansmith94 can commit a PR? :)

### PR DESCRIPTION
**Pull request by ryansmith94**
Closes #337 

Hey @moltar, tried to keep this as close to #105 as possible so I left out the generation of the results files from running `npm start`. Let me know if you need me to add those.

Rulr's performance was pretty surprising, I think the issue is that Rulr will find all of the errors in the object before throwing an error, I might implement a `bail` option for the object rule and see if that improves the performance.

### CODE REVIEW

**Comment by ryansmith94** [comment]
Ah forgot to use an exact version in the package.json, updating that now 👍

**Comment by ryansmith94** [comment]
Ok I'm done making changes.

**Comment by moltar** [comment]
Hey @ryansmith94, awesome. Thanks :)

**Comment by ryansmith94** [comment]
Just a heads up @moltar, it looks like you've got some issues in the results files. It looks like you might have stashed some changes or applied some stashed changes.

**Comment by moltar** [comment]
Oh yeah, crap, that does happen when I merge multiple things too quickly. Then the GitHub Actions step on themselves.

I deployed a fix, hopefully will self-resolve in a few minutes.

Thanks for the heads up! Probably need another GitHub Actions workflow to monitor for this :D

**Comment by ryansmith94** [comment]
Ah makes sense, no worries 👍 

Awesome, I'll take a look, thanks for the quick fix Roman. Must be early over there in Canada.

Haha yeah maybe. I guess there must be some way around it, perhaps a new results branch that just contains the images, kind of like how you would build a gh-pages site.

**Comment by moltar** [comment]
I’m in Vietnam 🇻🇳 now 😅

**Comment by ryansmith94** [comment]
Wow nice, sounds warm 😅

**Pull request merged**
