### PR TITLE
Updates ts-runtime-checks

### PR DESCRIPTION
**Pull request by mmamedel**
Library developer added this new feature that allows parseStrict and assertStrict... so I'm updating it. One thing I have noticed is that the docs svg has not updated one last pr... is this being re-created at build time or is something I need to add to the pr?

### CODE REVIEW

**Comment by moltar** [comment]
> One thing I have noticed is that the docs svg has not updated one last pr... is this being re-created at build time or is something I need to add to the pr?

All of the benchmark results and graphs should regenerate using GitHub Actions.

Can you please point out a specific case where it did not refresh?

---

Also:

> This branch cannot be rebased due to conflicts

**Comment by mmamedel** [comment]
> > One thing I have noticed is that the docs svg has not updated one last pr... is this being re-created at build time or is something I need to add to the pr?
> 
> All of the benchmark results and graphs should regenerate using GitHub Actions.
> 
> Can you please point out a specific case where it did not refresh?
> 
> Also:
> 
> > This branch cannot be rebased due to conflicts

I notice that `docs/results/preview.svg` shown in `README.md` is two months old, but the "top 3" packages changed. I quoted it because that's the SVG title, but it actually shows top 4.

I merged master into my branch and I just see:
> This branch has no conflicts with the base branch

Let me know if there is still a problem.
Thank you

**Comment by moltar** [comment]
I think the preview is toggled off by env? https://github.com/moltar/typescript-runtime-type-benchmarks/blob/929a5d0bb5d3a85dd7522983c2ce91d9bf208d0f/benchmarks/helpers/main.ts#L17

@hoeck Is the preview image static and needs to be manually re-generated or do we need to set the env var in the GitHub config to trigger the process?

**Comment by hoeck** [comment]
@moltar no the image is generated during one of the test runs that has the configured `NODE_VERSION_FOR_PREVIEW`:

https://github.com/moltar/typescript-runtime-type-benchmarks/blob/b9a326534d2ae7b57a7416a1e22d5ba31f8e0de5/benchmarks/helpers/main.ts#L10

Forgot to update this to 18 in my node-version update. I'll create a PR that fixes this and puts a note in the workflow so the next person updating node versions doesn't forget to update this.

That `TEST_PREVIEW_GENERATION` is to generate the image during development without running the full benchmark to reduce the update-reload cyle to a few seconds instead of minutes.

**Comment by hoeck** [comment]
@mmamedel thx for catching the outdated preview.

> I quoted "top 3" because that's the SVG title, but it actually shows top 4.

It shows the top 3 packages and one bar that shows the median score of the remaining packages ("...rest"). Was meant to be more of a colorful eye catcher that still does show something useful but takes not too much space.

**Comment by mmamedel** [comment]
> @mmamedel thx for catching the outdated preview.
> 
> > I quoted "top 3" because that's the SVG title, but it actually shows top 4.
> 
> It shows the top 3 packages and one bar that shows the median score of the remaining packages ("...rest"). Was meant to be more of a colorful eye catcher that still does show something useful but takes not too much space.

Oh, got it..
Question: how hard would it be to order the top 3 preview by result instead of by name?

**Comment by hoeck** [comment]
> Question: how hard would it be to order the top 3 preview by result instead of by name?

Not sure any more but I think I tried to sort it, `prepareValues` is sorted by ops and the vega spec contains a sort param for each graph too:

https://github.com/moltar/typescript-runtime-type-benchmarks/blob/master/benchmarks/helpers/graph.ts#L125

but because of the graph format ["repeat"](https://vega.github.io/vega-lite/docs/repeat.html) (rows & columns with 1 embedded bar chart) it somehow is ignoring the sort and falling back to something else.

Mhhh, in app.tsx I use a completely different approach to sorting:

https://github.com/moltar/typescript-runtime-type-benchmarks/blob/master/docs/app.tsx#L210

maybe I should try that in the preview image.

**Comment by mmamedel** [comment]
@hoeck Do you any to include the update to preview on this pr or leave it to another one?

**Comment by hoeck** [comment]
> @hoeck Do you any to include the update to preview on this pr or leave it to another one?

@mmamedel no I will do that in a separate PR

**Comment by GoogleFeud** [comment]
Creator of ts-runtime-checks here: is this going to be merged?

**Comment by moltar** [comment]
@mmamedel Could you fix up the PR, please? Thanks!

**Review by hoeck — APPROVED** [review]

**Pull request merged**
