### PR TITLE
added AJV, who is the by far most popular validator

### PR DESCRIPTION
**Pull request by marcj**
and claims to be the fastest.

### CODE REVIEW

**Comment by marcj** [comment]
I see you tried to workaround the Marshal issue by placing different snapshots into its tests. The tests show that it works correctly now, so I don't know what was the issue:

```
Case Class: marshal › should fail validation when prop is missing

    expect(received).toMatchSnapshot()

    Snapshot name: `Case Class: marshal should fail validation when prop is missing 1`

    Snapshot: [TypeError: Cannot add property boolean, object is not extensible]
    Received: [Error: Invalid]

      78 | 
      79 |     expect(err).toBeTruthy();
    > 80 |     expect(err).toMatchSnapshot();
         |                 ^
      81 |   });
      82 | 
      83 |   it('should fail validation when number is not negative', async () => {
```

**Comment by marcj** [comment]
I corrected that marshal snapshot again so that tests are green again

**Comment by moltar** [comment]
I don't think `ajv` is relevant here, because it is just a generic data validator. It does not provide type safe guarding of the return object on success.

**Comment by marcj** [comment]
Don't toi and runtypes suffer from the same criteria? They are like ajv only tested as validators, and probably are only validators. If so, why are they included and not the one with 25million downloads/month?

**Comment by moltar** [comment]
Actually only `ts-json-validator` suffers from the same problem. And either it will be fixed or I'll remove it completely. I added it prior by my own mistake.

**Comment by marcj** [comment]
And [ui-ts](https://github.com/moltar/typescript-runtime-type-benchmarks/blob/master/cases/io-ts.ts#L47), no?

**Comment by marcj** [comment]
Ah I see, I guess `decode` does the deserialization. Well then ts-json-validator should probably be removed. You can close this PR then, or create a whole new section of cases only for validation - which would be equally interesting.

**Comment by moltar** [comment]
No, you can check the code. Every Case class extends Case and implements Case.

The interface states that `validate` method must return `DataType` type.

If this is not satisfied, TypeScript will produce an error:

Example:

image

```
74   validate() {
     ~~~~~~~~

cases/marshal.ts:74:3 - error TS2416: Property 'validate' in type 'MarshalCase' is not assignable to the same property in base type 'Case'.
  Type '() => {}' is not assignable to type '() => Readonly<{ number: number; negNumber: number; maxNumber: number; string: string; longString: string; boolean: boolean; deeplyNested: { foo: string; num: number; bool: boolean; }; }> | Promise<...>'.
    Type '{}' is not assignable to type 'Readonly<{ number: number; negNumber: number; maxNumber: number; string: string; longString: string; boolean: boolean; deeplyNested: { foo: string; num: number; bool: boolean; }; }> | Promise<...>'.
      Type '{}' is missing the following properties from type 'Promise<Readonly<{ number: number; negNumber: number; maxNumber: number; string: string; longString: string; boolean: boolean; deeplyNested: { foo: string; num: number; bool: boolean; }; }>>': then, catch, [Symbol.toStringTag], finally

74   validate() {
```

**Comment by moltar** [comment]
> Well then ts-json-validator should probably be removed

I will, if the author won't add that. I think it is possible to add it to this package. I'll give it some more time, and if not added, I'll remove it.

See https://github.com/ostrowr/ts-json-validator/issues/27

**Pull request closed without merging**
